# Generated by Django 5.1.4 on 2025-02-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_fcm_token_alter_user_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
