# Generated by Django 5.1.4 on 2025-02-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
    ]
