# Generated by Django 5.1.4 on 2025-02-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_booking_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service_type',
        ),
    ]
